pub const SCREEN_WIDTH: i32 = 80;
pub const SCREEN_HEIGHT: i32 = 65;

pub const MAP_WIDTH: i32 = 60;
pub const MAP_HEIGHT: i32 = 45;

pub const MESSAGES_HEIGHT: i32 = SCREEN_HEIGHT - MAP_HEIGHT;
pub const MESSAGES_WIDTH: i32 = MAP_WIDTH;

pub const STATS_PANEL_WIDTH: i32 = SCREEN_WIDTH - MAP_WIDTH;
pub const STATS_PANEL_HEIGHT: i32 = SCREEN_HEIGHT - 35;

pub const INFO_PANEL_WIDTH: i32 = SCREEN_WIDTH - MAP_WIDTH;
pub const INFO_PANEL_HEIGHT: i32 = SCREEN_HEIGHT - STATS_PANEL_HEIGHT;


pub const LOG_MEMORY: i32 = 100;
